language: java
jdk:
- oraclejdk8

branches:
  only:
  - master
  - "/^v[0-9]+\\.[0-9]+/"

after_success:
- test "${TRAVIS_PULL_REQUEST}" == "false" && test "${TRAVIS_TAG}" != "" && mvn deploy --settings travis-settings.xml
- mvn dockerfile:build -pl SensorThingsServer
- mvn dockerfile:tag@tag-version -pl SensorThingsServer
- mvn dockerfile:push@push-latest -Ddockerfile.useMavenSettingsForAuth=true -pl SensorThingsServer --settings travis-settings.xml
- mvn dockerfile:push@push-version -Ddockerfile.useMavenSettingsForAuth=true -pl SensorThingsServer --settings travis-settings.xml

sudo: required

services:
  - docker

env:
  global:
  # travis encrypt BINTRAY_USER=[username]
  - secure: Xdua67Xl6XNm+EpNaADXMsGJ4DUHaQ7EcY1PgVXXkUBNJ9JbK+b/bWrYV/bJpTP2CDnTI3eNSEhOKe+tFwD7KV07q86i2sg12jUJlwNBt0sUOWE4MSJdBOJVogrUzJ+NZGWGzGTAJBHXDOpPb8y9s6XAVUGUbK9MDrvYGzVHKUtVD0rybdJgNdJ38AQPiDQaSpu/E2obHRXiT5qHOWO7Khfd87+UaByekHpVyObefkhh0z0/q57dLOJWgh3Lb37S1LZOS8/1C835uhU8GHu0PQOORxVFCvfhrKa+hKt+NwXOjJSukdXKSsBer4IDMXgJt7244EaUpxpAj+E849yaX6NANyC7CT+mGWAqxce3L7Bo57B9ctWQ9mHOtI6rQpfpslCV8Y7go7jzwmlHZwwHLhMb7n4PNyjNxOTzbL985iF+gK3jmC367kgNjC0Q89zOkw3m8pQh2vJSHNojb3IFjHZpAAhJ04r7/f6jB/jKUOr91Cf/fpykfOuvXjRsNLLj2vj238OX+jfToTCX93MMVZP7AsW/QTDHwm116iVWkbzm1GWXdmcox0et6aVerOVP3t//TpWIXXl9x4JWGYBUlH7+dkvNismX5e7aM/sgOZfD+9DdJWbJ5y1ortgaJ0r+wOtme9y5yPcR3JK/nBvs9E/Un28hENyYvHFYVpkYSwU=
  # travis encrypt BINTRAY_API_KEY=[api key]
  - secure: Ko3nZzc9zo6gqcVZ87+jt2JU1rKrhFUWc23Iv2XLOvXgmNEkzwaM/wnBM810vrt9zQ/k2GHg4RfW7znEi0YyiQBozgY/ZHX63DHMEICNGOA8QwHgkVLWEqv7rVmG+wk/ApEfRiKOz9zN2088m64fyYL7fVaAnH8pb9hmfY1fZ6mVBNWIItVv036xwiAjsYd76+9VlG4ToU7CgKEKEiNuylQwnndNooTqBSljUrRjEhsIHQihb0jMoLe6kKwKlNIBHJvKAZrhQZ9Gara3WNaG2K/5MEUdhb1UaY/WBiSV6u6OQq7cr3cDgNPh4OGHUrcKEHUcrmqLwbsq2oijZQYtd7Uv0B4uJZZmZf3CoK2lm896bJXCsKCOnEw1kvDDrO4MbsBvSHYR582W2c5i5SKiJv41c1mrTkFrmZJQrC7OALO02PELghdmxjq3nnvYdFEg8WHBWemmMe+Pm90Q5CzG/8/4J80Z//jEJu23BY9ubAj5Kgjvrt0l1x0PHPxGL2AVX7kCOkeA0+R6bJyMwUG+p0YnlQB17OBKlk5aL+1YpN8Anrw5xTSIHPdeqYJXUa7EZmYlAD3T6W0grdcmpRHTC1dJPhRGh8fHBWoFrYdjqbHe/Ry3miCXoPXMGPhGFy4eDdqhesHFt9NP6j0RvOufml4TDoxjPJI2SzYlTnlg4NE=
  # travis encrypt DOCKER_USERNAME=[username]
  - secure: P+z967jQUEzWJkAtCUMWotUr2Ft/FkKYHJmXK2/LlzsFFSB7HP+wOlxLNVMFauek1M5ZZ5jyt1s0nvmftSP4STSIfE63I05Wkjz9A5rrmG4SzUvYFF5mDOS5fa8YTNgnZhBUBP2Ip6WtVnlbbi+bxK44GJFF70ymofWAy+uEmJ+qQFf+PMYa8CS4gY3jGrV/YCY/a3fl8tL240VdjDL0Bv35MTEtMH9x3DR04mAAFlq+6cuaYq/m8eTwivNV7BcC/hz69SroWIk7RnAht6pcVT08W32hib67TXF4zt5kljxuH7hsG+trh9bZFUh2XMGXTZV0ps89WFI6/qTe0olrj++xYuRgglhhUUmpqY3npxGpsq7Z65xoK6UyInVuy+JVUHm77/QIucQY6bxpWx1NyEVUSaQpLGVXp/ABZ6n98OJcosf1e18urBVoV8F2rZYNcRLtuHwmw1rtpI2PCZOvc4ewnJy6hGKmoDa1CzK7Xj8hQ9wtKR9+0m9x7X+qZ/vrfaN7jJ7uLPfgzgZlip4mWTkFw6GSeso6iYjgv+ARHPFwfe46M3K1QzNq5CRLrn++f2r2doWBfpYtd06YYKH8JT8u/q1IFL8nrqwJ6jT22CXO06+EZV5V5ZSEtrrK9/kII81LLG4xIFyvZ5C2csVLdzGg2Mdcna+UZU6zCbGvT3g=
  # travis encrypt DOCKER_PASSWORD=[username]
  - secure: tMi5jaBO/iaK/Lc3x5WTXqgGfP35v4KZFvc5AD59qEETI1GmQ22e0maqq5YZfZWz5g3ZzS2irWRzKfrYln1lgx2LJ1AI4qHW5CQI0dlEj7OIxzK8FXlJz5tkovlfIHkniL5XyFc4eUSo+d878h8CyNRDoKQlGQie3rP0oaMl5r+CfhsdA4FRxWFY3xerlxUF20XDceVOc2tW7+HB7ROf/jFzlSxMqShbmHOvmcBxMYChPEv9xDsV16LJ+dHAg5H+DNBwFwaoMzFRmFTECrQD5xroo+Jn9eoDvWQ1OXJNQCRulbdZcq/rUOE7YQqjTuO3/aGocNPNH+5GUCf/nDSfweCPoBtaaZU7anWfJbzP9DwA6bQ490mBzgSas8n/ar0zgD8+sjwcghcPVPqH7+ZLXvw/GRs+FVd4eFs2iMgA8CoIGPqs20sYj1PGULCLeQnCDGujQnAfXMsmd49pRlOAnP4d5dgchETK2jf05UPX3Ou65yJght2NoRl5x+NPo8iei/nGtGIM8hSzyb0nPt6TiznYPGB5p0Fob2r23H/uyFVgKriEstYR7STCb1asKFZrARmVhYmngmsO/UX8poSj500ipSi5ymgVZZ/u6361Ghy38c1la62H+DgylPR3Of21DGlb11smfgfhggYJ/f7pMT1tV+Prjr+k9WhD8i2i2Mc=
